### PR TITLE
Remove global function `window.Class`

### PR DESCRIPTION
**Pull request by mfairchild365**

### CODE REVIEW

**Comment by kabel** [comment]
I guess that works, if the script is loaded through require.

Looks like this project too, needs to have the tests updated to not rely on pyrus (travis fail).

**Comment by mfairchild365** [comment]
:( RIP Pyrus

**Comment by mfairchild365** [comment]
I'm going to work on getting the tests working, please don't merge until I have that ready.

**Comment by mfairchild365** [comment]
@kabel Tada!

**Comment by kabel** [comment]
Would it have been easier to use phpunit to run the tests? It can handle phpt too.

**Pull request merged**
